[package]
name = "accountant"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.215", features = ["derive"] }
clap = "4.5.21"
dashmap = "6.1.0"
lazy_static = "1.5.0"
test-case = "3.3.1"
fern = "0.7.0"
chrono = "0.4.38"
log = "0.4.22"
rayon = "1.10.0"
